Helps to stop 504 errors
10up/wp-local-docker pull request #36
Opened 2017-05-31 08:27 UTC by c9dd

As I can tell at the moment this helps to stop 504 errors, but I will keep an eye on this and tweak if/when needed.

2017-07-26 05:15 UTC, tlovett1 commented
I need to test this. Also needs formatting fixes.

2019-04-01 20:22 UTC, cmmarslender requested changes

2019-04-01 20:22 UTC, cmmarslender commented on config/nginx/default.conf
> +        fastcgi_connect_timeout                 10;
We have some similar settings to these in V2, with slightly different values. I'd prefer to match these up to V2 for consistency: https://github.com/10up/wp-local-docker-v2/blob/master/src/config/nginx/develop.conf#L50

The main one that changed was the fastcgi_read_timeout on that config. Are you having issues that were fixed with a send timeout change?

2019-04-01 20:22 UTC, cmmarslender commented on config/nginx/default.conf
> +        #fastcgi_param  HTTPS                   $https if_not_empty;
I think we can just leave this particular line uncomment always and It should work fine on the backend

2019-04-01 20:22 UTC, cmmarslender commented on config/nginx/default.conf
> +        #fastcgi_pass wordpress:9000;
There isn't a service called `wordpress` - We shouldn't need this line with the fastcgi_pass that is already in this block which passes to `phpfpm`

2019-04-01 20:22 UTC, cmmarslender commented on config/nginx/default.conf
> +        #fastcgi_param  SSL_PROTOCOL            $ssl_protocol if_not_empty;
I don't think these 4 lines are required to be passed to `phpfpm` - As far as I'm aware, WordPress just looks and checks if `https` is on when doing anything ssl related - See function declaration here: https://developer.wordpress.org/reference/functions/is_ssl/

2019-04-01 21:47 UTC, jeffpaul commented
@c9dd mind reviewing and responding to the feedback on the PR?

2019-09-05 14:57 UTC, jeffpaul commented
@c9dd are you able to review and respond to the feedback on this PR?

2019-09-05 14:58 UTC, jeffpaul commented
Resolves #29.

2019-09-16 13:45 UTC, jeffpaul commented
@c9dd note that we're archiving WP Local Docker in favor of the newer [WP Local Docker v2](https://github.com/10up/wp-local-docker-v2), so please update to the v2 version and we can discuss any further issues you see in its respective repo.  Thanks!

2019-09-16 13:54 UTC, closed without merging