Automate WordPress installation
10up/wp-local-docker pull request #64
Opened 2017-12-17 14:00 UTC by benoitchantre

Not tested on Windows. Can someone test it?

Closes #45.

2017-12-19 02:58 UTC, Viper007Bond commented
It works-ish on Windows.

```
C:\work\wp-local-docker\bin>setup.bat
"WordPress config file not found. Installing..."
Failed loading /usr/local/lib/php/extensions/no-debug-non-zts-20151012/xdebug.so:  /usr/local/lib/php/extensions/no-debug-non-zts-20151012/xdebug.so: cannot open shared object file: No such file or directory
Downloading WordPress 4.9.1 (en_US)...

Warning: mkdir(): Permission denied in phar:///usr/local/bin/wp/php/WP_CLI/FileCache.php on line 265
md5 hash verified: 111ecbfc98633103e1fc1105c0c00c76
Success: WordPress downloaded.
Failed loading /usr/local/lib/php/extensions/no-debug-non-zts-20151012/xdebug.so:  /usr/local/lib/php/extensions/no-debug-non-zts-20151012/xdebug.so: cannot open shared object file: No such file or directory
Success: Generated 'wp-config.php' file.
Failed loading /usr/local/lib/php/extensions/no-debug-non-zts-20151012/xdebug.so:  /usr/local/lib/php/extensions/no-debug-non-zts-20151012/xdebug.so: cannot open shared object file: No such file or directory
ERROR 1007 (HY000) at line 1: Can't create database 'wordpress'; database exists
Failed loading /usr/local/lib/php/extensions/no-debug-non-zts-20151012/xdebug.so:  /usr/local/lib/php/extensions/no-debug-non-zts-20151012/xdebug.so: cannot open shared object file: No such file or directory
2/6 --title=<site-title>: Title
```

However I think some improvements can be made:

* Prompt for the password too or capture the generated password and then display it at the end of the script rather than being buried mid-script.
* Why are you removing themes? For example I personally I prefer to develop plugins using one of those rather than Twenty Seventeen.
* I also don't get the reasoning behind removing the widgets. Why would I want an empty sidebar?
* The Developer plugin should probably be automatically activated.

2017-12-19 21:42 UTC, benoitchantre commented
Thank you @Viper007Bond for your feedbacks and tests.

I think the warnings below were already on the `master` branch. Can you confirm?
```
Failed loading /usr/local/lib/php/extensions/no-debug-non-zts-20151012/xdebug.so:  /usr/local/lib/php/extensions/no-debug-non-zts-20151012/xdebug.so: cannot open shared object file: No such file or directory
Warning: mkdir(): Permission denied in phar:///usr/local/bin/wp/php/WP_CLI/FileCache.php on line 265
Failed loading /usr/local/lib/php/extensions/no-debug-non-zts-20151012/xdebug.so:  /usr/local/lib/php/extensions/no-debug-non-zts-20151012/xdebug.so: cannot open shared object file: No such file or directory
```

The automation tasks that were proposed are based on my personal workflow and preferences. Before submitting a PR, I asked for suggestions on #45. I received many +1 without other suggestions.

Most of the times I start a theme from [_s](https://github.com/Automattic/_s) and prefer to use the [Monster Widget](https://fr.wordpress.org/plugins/monster-widget/) Plugin to test widgets when they are needed.

The permalink settings are based on [Yoast article](https://yoast.com/wordpress-seo-url-permalink/).

I'll push some improvements based on your feedbacks.

I'd like also to define some constants in wp-config.php, but I get errors when the commands are preceded by `docker-compose exec --user www-data phpfpm`. Here's what I generally define in wp-config.php:

```
define( 'DISALLOW_FILE_EDIT', true );
define( 'WP_POST_REVISIONS', false );
define( 'WP_DEBUG', true );
define( 'SAVEQUERIES', true );
```

2017-12-19 23:08 UTC, Viper007Bond commented
Widgets: Let's install, activate, and add the Monster Widget then. I've used it too -- it's a good plugin. :)

Permalinks: this is just a local development install so I think it's better to keep to unofficial standards rather than worrying about SEO.

Constants: What if I'm developing a plugin that is related to revisions? Again, this is a development build so I think we should try to stay as close to vanilla WordPress as possible, namely not disabling file edits and post revisions. Those may make perfect sense in production, but I'd argue they don't for development.

2018-02-04 15:41 UTC, carl-alberto commented
Hi guys, thanks for this addition in automating the installation of WP, we heavily use this as a starting point in our local development and most of the time we start from a blank slate of WP, meaning no widgets, all the default page, post, comment is deleted and extra twentyXXX themes are deleted. If there will be a Y/N option on the setup script to start with a blank slate or with defaults, that would be excellent.

Another thing that might be beneficial to other theme developers is an additional script to have an option to quickly generate Underscores based theme after the initial automated setup. Would love to help out with a PR or a separate issue regarding this if this is a good idea. Thank you!

2018-02-04 17:06 UTC, benoitchantre commented
Thank you for your feedback @carl-alberto. I'll add an option to keep the default install, that's a good idea.

> Another thing that might be beneficial to other theme developers is an additional script to have an option to quickly generate Underscores based theme after the initial automated setup.

You can simply use `docker-compose exec --user www-data phpfpm wp scaffold _s` with your desired parameters. I'm not sure its worth duplicated all the prompts for this command.

> Would love to help out with a PR or a separate issue regarding this if this is a good idea. 

I think the best way to help now is to get more feedbacks in this conversation.

2018-02-04 23:12 UTC, Viper007Bond commented
Even easier: `wp scaffold _s` inside of the `bin` directory! :)

2018-02-08 09:59 UTC, carl-alberto commented
thanks @benoitchantre, looking forward to test it

thanks for the tip @Viper007Bond :)

2018-02-08 20:36 UTC, benoitchantre commented
Should we install and activate Gutenberg by default ?

2018-02-08 21:08 UTC, benoitchantre commented
You can now test it @carl-alberto.

2018-02-10 17:34 UTC, carl-alberto commented
@benoitchantre tested on ubuntu 16.04 & macOS 10.13 and its looking good, few feedback:

- If its ok with @Viper007Bond to have the monster widget having a prompt to be installed or not?
- +1 for Gutenberg as an optional install 
- Would it be a good idea to put all the options as parameters in a one liner command like `sh bin/setup.sh --title="Site Title" --email="email@test.com" .....` ?

2018-02-16 22:17 UTC, benoitchantre commented
> Would it be a good idea to put all the options as parameters in a one liner command like sh bin/setup.sh --title="Site Title" --email="email@test.com" ..... ?

It's a good idea @carl-alberto to reduce the number of prompts, but I will need some help to make it work in both environments.

I think Gutenberg could be added and activated by default: projects developed now need to be tested with Gutenberg.

2018-02-17 02:59 UTC, carl-alberto commented
sure thing @benoitchantre, which environment you need help with? 

Sounds good if Gutenberg is activated on default

2018-02-18 21:21 UTC, benoitchantre commented
Can you test on Windows @carl-alberto ? I was able to add the parameters but I have no environment to make some tests on Windows.

Other than that, I think more feedbacks would be welcome, especially from the maintainers of this project (cc. @tlovett1, @cmmarslender).

2018-02-22 06:37 UTC, benoitchantre commented
I will probably add a fourth (optional) parameter to launch a multisite installation rather than a single site installation.

2018-02-23 16:30 UTC, tlovett1 commented
Very cool! I'll review sometime in the next few days.

2018-03-08 20:50 UTC, benoitchantre commented
Is everything working properly on Windows @Viper007Bond?

2018-03-11 04:05 UTC, carl-alberto commented
@benoitchantre tried to test on windows and getting an error, I turned on echo to troubleshoot:

```
REM Parameters
SET TITLE=title
SET ADMIN_USER=admin
SET ADMIN_EMAIL=test@test.com
if not defined EMPTY_CONTENT set EMPTY_CONTENT=true
if not "true" == true SET EMPTY_CONTENT=false
if not defined MULTISITE set MULTISITE=false
if not "false" == true SET MULTISITE=false
= was unexpected at this time.
if "y" = "" (
```

Seems, there is a missing closing parenthesis around setup.bat lines 15-26.

For Linux/Mac, it is looking good.

2018-03-11 21:26 UTC, benoitchantre commented
Thank you @carl-alberto. It should be fixed now.

2018-03-21 19:35 UTC, benoitchantre commented
Do you have some to time to review this PR @tlovett1?

2018-03-22 00:25 UTC, tlovett1 commented
@cmmarslender can you take a look?

2018-04-03 17:13 UTC, cmmarslender requested changes

2018-04-03 17:13 UTC, cmmarslender commented on bin/setup.sh
> +TITLE=$1
Since this now requires additional parameters to function properly, we should add validation to make sure the script doesn't try to run without required input supplied. I didn't realize this had changed, and it was attempting to run and getting a bunch of errors by just running `./bin/setup.sh`

Alternatively, since we prompt for parts of this data, it probably makes sense to just prompt for all the data we need. Either way, this shouldn't attempt to run without valid parameters.

2018-04-03 17:13 UTC, cmmarslender commented on bin/setup.sh
> +docker-compose exec --user www-data phpfpm wp db create
`wp db create` isn't necessary, except in the situation where you drop the database (when reinstalling). Docker creates the WordPress DB automatically on start. This should probably be moved inside the "reinstall" prompt above, otherwise it will just produce an error which is likely to lead to confusion

```
ERROR 1007 (HY000) at line 1: Can't create database 'wordpress'; database exists
```

2018-04-03 17:13 UTC, cmmarslender commented on bin/setup.sh
> +docker-compose exec --user www-data phpfpm wp plugin install gutenberg --activate
This should probably be behind a prompt "Do you want to install gutenberg?" - Don't want to enforce every site needs to use gutenberg, since this will very likely be used for existing sites that don't use gutenberg.

2018-04-03 17:13 UTC, cmmarslender commented on bin/setup.sh
> +docker-compose exec --user www-data phpfpm wp plugin install developer --activate
This should also likely be behind a prompt

2018-04-03 19:38 UTC, benoitchantre commented on bin/setup.sh
> +docker-compose exec --user www-data phpfpm wp db create
Thanks for having seen that. We can even use `wp db reset` inside the reinstall prompt above.

2018-04-03 21:19 UTC, merged

2018-04-03 21:26 UTC, benoitchantre commented
Thanks for the review @cmmarslender.